apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seda-data-proxy.fullname" . }}-config
data:
  config.json: |
    {
      "routes": [
        {
          "path": "/*",
          "upstreamUrl": "https://swapi.dev/api/",
          "methods": ["GET"]
        }
      ]
    }
