apiVersion: v1
kind: Service
metadata:
  name: {{ include "seda-data-proxy.fullname" . }}
  labels:
    {{- include "seda-data-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "seda-data-proxy.selectorLabels" . | nindent 4 }}
