name: 🧹 Git Checks
on: [pull_request]

jobs:
  block_fixup:
    name: "Block Fixup Commit Merge"
    runs-on: ubuntu-latest

    steps:
      - name: 🛃 Checkout repository
        uses: actions/checkout@v4

      - name: 💂 Block Fixup Commit Merge
        uses: sedaprotocol/block-fixup-merge-action@v1.0.0
